name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: "挨拶"
        run: echo "Nice to meet you!!"

      - name: "名前を言う"
        run: echo "My Name is Yumiko!!"

      - name: "趣味を話す"
        run: echo "I love reading books!!"